# Generated by Django 6.0.6 on 2026-06-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('reference_source', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.PositiveIntegerField(unique=True)),
                ('quantite', models.IntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
