# Generated by Django 6.0.6 on 2026-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('vente_id', models.PositiveIntegerField()),
                ('client_id', models.PositiveIntegerField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('format', models.CharField(choices=[('TICKET', 'Ticket de caisse'), ('PDF', 'PDF professionnel')], default='TICKET', max_length=10)),
                ('statut', models.CharField(choices=[('PAYEE', 'Payee'), ('EN_ATTENTE', 'En attente')], default='PAYEE', max_length=15)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
